# Generated by Django 3.1.2 on 2021-01-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch_entry',
            fields=[
                ('Batch_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Chick_arrived', models.IntegerField()),
                ('Arrived_date', models.DateField()),
                ('Arrived_time', models.TimeField()),
                ('Matralty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trays', models.IntegerField()),
                ('Feed', models.IntegerField()),
                ('Medicine', models.CharField(max_length=50)),
                ('Matralty_on_days', models.IntegerField(default=0)),
                ('Batch_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poultry.batch_entry')),
            ],
        ),
    ]
