# Generated by Django 3.1.2 on 2021-02-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poultry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='Date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='production',
            name='Time',
            field=models.TimeField(default=None),
        ),
    ]
