# Generated by Django 3.1.2 on 2021-02-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poultry', '0003_remove_production_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_entry',
            name='Live_birds',
            field=models.IntegerField(default=0),
        ),
    ]
